// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// countsToProbs
NumericVector countsToProbs(NumericVector x);
RcppExport SEXP _dissPackage3_countsToProbs(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(countsToProbs(x));
    return rcpp_result_gen;
END_RCPP
}
// vectorToCounts
NumericVector vectorToCounts(NumericVector x, NumericVector breaks);
RcppExport SEXP _dissPackage3_vectorToCounts(SEXP xSEXP, SEXP breaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    rcpp_result_gen = Rcpp::wrap(vectorToCounts(x, breaks));
    return rcpp_result_gen;
END_RCPP
}
// weightedSelection
NumericVector weightedSelection(NumericVector x, NumericVector probs);
RcppExport SEXP _dissPackage3_weightedSelection(SEXP xSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(weightedSelection(x, probs));
    return rcpp_result_gen;
END_RCPP
}
// divv
NumericVector divv(NumericVector x);
RcppExport SEXP _dissPackage3_divv(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(divv(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _dissPackage3_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dissPackage3_countsToProbs", (DL_FUNC) &_dissPackage3_countsToProbs, 1},
    {"_dissPackage3_vectorToCounts", (DL_FUNC) &_dissPackage3_vectorToCounts, 2},
    {"_dissPackage3_weightedSelection", (DL_FUNC) &_dissPackage3_weightedSelection, 2},
    {"_dissPackage3_divv", (DL_FUNC) &_dissPackage3_divv, 1},
    {"_dissPackage3_rcpp_hello_world", (DL_FUNC) &_dissPackage3_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_dissPackage3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
