# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countsToProbs <- function(x) {
    .Call(`_dissPackage3_countsToProbs`, x)
}

vectorToCounts <- function(x, breaks) {
    .Call(`_dissPackage3_vectorToCounts`, x, breaks)
}

weightedSelection <- function(x, probs) {
    .Call(`_dissPackage3_weightedSelection`, x, probs)
}

divv <- function(x) {
    .Call(`_dissPackage3_divv`, x)
}

rcpp_hello_world <- function() {
    .Call(`_dissPackage3_rcpp_hello_world`)
}

